Repository stweeks-pdx/ECE585-LLC-GRP1, pull requests merged in 2024-11, with the labels that each got.

#3 Cleaning up code to separate trace code from main code
  include/trace.h
  src/Makefile
  src/main.c
  src/trace.c
Labels: enhancement

#4 Fixing my dumb mistake
  include/trace.h
  src/main.c
  src/trace.c
Labels: bug

#6 Adding linux-friendly Test Plan. Updated Test Plan
  Cache Test Plan.docx
  doc/testPlan
Labels: documentation

#8 Testing traces for II header plans
  testing/II/d_i_A.din
  testing/II/d_i_B.din
  testing/II/d_ii_A_2.din
  testing/II/d_ii_A_3.din
  testing/II/d_ii_C.din
Labels: enhancement
